version: "3.3"

services:
  manga:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    
    volumes:
      - /mnt/storage1/manga:/data
      # - /home/wutipong/manga:/data
    ports:
      - "6699:80"
    networks:
      - backend
    restart: "unless-stopped"


  db:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    expose:
      - "5432"
    environment: 
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "manga"
    restart: unless-stopped

networks:
  backend:

volumes:
  db-data: