version: "3.3"

services:
  manga:
    depends_on:
      - mongo
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    environment: 
      MANGAWEB_DB: "mongodb://root:password@mongo"
      MANGAWEB_IMAGE_PATH: /data
    volumes:
      - ./data:/data
    ports:
      - "8080:80"
    networks:
      - backend

  mongo:
    image: mongo
    networks:
      - backend
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

networks:
  backend: