name: Publish Latest Docker image
on:
  push:
    branches:
      - master
  release:
    types: [ published ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: true
          build-args: |
            VERSION=${{steps.tagger.outputs.tag}}
          cache-from: type=registry,ref=wutipong/mangaweb:latest
          cache-to: type=inline
          tags: wutipong/mangaweb:latest
