name: Publish Docker image
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2

      - name: get the version
        id: get_version
        uses: battila7/get-version-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          build-args: |
            VERSION=${{ steps.get_version.outputs.version-without-v }}
          cache-from: type=registry,ref=wutipong/mangaweb:latest
          cache-to: type=inline
          tags: wutipong/mangaweb:latest
